### ISSUE TITLE
getting onfailure() in getIceServers() method.

### ISSUE THREAD

**Issue by mjchangdofm** [vivek1794/webrtc-android-codelab#32]
Hi,

I'm a beginner of webrtc and trying to review your examples. I tried to get Ice server from xirsys with my info...but failed.
Could you please review my code?
I also tried to get ice server without "<>" in codes....also met exception...please help.

1)     byte[] data = new byte[0];
        try {
            data = ("<MJXXXX>:<93ab0328-d0fd-11e8-b652-xxxxxxxxxxxx>").getBytes("UTF-8");
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        }
2)        public static final String API_ENDPOINT = "https://global.xirsys.net";
3)      public interface TurnServer {
    @PUT("/_turn/<MyFirstApp>")
    Call<TurnServerPojo> getIceCandidates(@Header("Authorization") String authkey);
    }

4) onFailure() with
java.io.EOFException: End of input at line 1 column 1 path $
   at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1401)
   at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:549)
   at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
   at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFa
   at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:37)
   at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:25)
   at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:119)
   at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:218)
   at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:112)
   at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
   at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
   at java.lang.Thread.run(Thread.java:762)

Thanks in advance.

**Comment by shahidcodes** [comment]
You can use public available stun/turn server. You can find list [here](https://gist.github.com/sagivo/3a4b2f2c7ac6e1b5267c2f1f59ac6c6b)
