### ISSUE TITLE
node error

### ISSUE THREAD

**Issue by wirteEable** [vivek1794/webrtc-android-codelab#50]
TypeError: mime.lookup is not a function
    at Server.respond (G:\pengwb\webrtc-android-codelab-master\signalling\node_modules\node-static\lib\node-static.js:348:28)
    at G:\pengwb\webrtc-android-codelab-master\signalling\node_modules\node-static\lib\node-static.js:64:22
    at FSReqWrap.oncomplete (fs.js:155:5)

**Comment by nanisanjay** [comment]
go to  \signalling\node_modules\node-static\lib\node-static.js

add  **var mime=require('mime-types');**

then npm update 
it will work now.
